### ISSUE TITLE
GitHub 2FA support

### ISSUE THREAD

**Issue by ShadowOfANBU** [tillson/git-hound#7]
I create a config file in the same directory, where git-hound binary reside but, when I execute the binary file, it say "config.yml was not found". When I try to run the config. yml through the external command "--config-file", then it says the whole path was not found. So where we put the file.

My go version is: 1.13

**Comment by tillson** [comment]
Hey there,
Sorry for the delay in the triage.

I've just tested this with the latest release binary: https://github.com/tillson/git-hound/releases and could not reproduce the problem. Are you running from source? If so, let me know what OS you're using and we can try to get to the bottom of this.

**Comment by skynet594** [comment]
When i create the config.yml file and run the tool it gives me to errors "can login into github with 
"myusername". the github account i created has no 2F authentication turned on as you descriped.
When i run it again it gives me the error "config.yml was not found". I'm running it on kali amd64..

**Comment by gabemarshall** [comment]
I just started getting this error recently as well (btw great tool @tillson 👍) - I haven't had a chance to dig into it much yet, but line 147 of `internal/app/search.go` is where it's faulting for me. I figured maybe Github had made some changes to the search that may have broken the regex matching 🤷‍♂️

**Comment by tillson** [comment]
Managed to reproduce this. I suppose we'll need to add better catching of 2FA. 
Thanks for the report: consider this triaged. I'll look into it this week.

**Comment by tillson** [comment]
Hey, this should be fixed now! Check out master.

**Comment by tillson** [comment]
Closing this for now. if any similar issues arise, let me know!

**Comment by Anne272732** [comment]
Hi Tillson,

I have the same issue, i can't loggin with my Github account (no 2FA activate), i used a Digital Ocean VPS to test it.

Here you can see the screenshot of my process ( i've downloaded the version1.1 as you can see):

https://www.screencast.com/t/1ciQ17qwi2

Uname -a

https://www.screencast.com/t/lYRQwx0i

Could you take a look?

Regards

**Comment by tillson** [comment]
Hey @Anne272732, thanks for updating this.
The problem is that even if 2FA isn't enabled, GitHub requires you to do a 2FA code when you log in from a new computer (so it catches the Digital Ocean VPS). I'll try to get this fixed this weekend!

I've updated the issue title to reflect what's really going on.

**Comment by Anne272732** [comment]
Hi @tillson,

Thanks for the response... Perfect !!

I'll check again when you fix it !!

Regards

Anne272732

**Comment by tillson** [comment]
Fixed: https://github.com/tillson/git-hound/pull/11

**Comment by Anne272732** [comment]
Hi @tillson,

Could you take another look at the issue?

In my case, the issue is still present with the last version:

https://www.screencast.com/t/xRDXdR34AS5

Regards

**Comment by tillson** [comment]
Check out https://github.com/tillson/git-hound/issues/12. Should have a fix shortly since it's just the 2FA stuff with a different endpoint!

**Comment by tillson** [comment]
As an update, this is now resolved in v1.2.1.

**Comment by AshKumar06** [comment]
I think the problem still persist , I downloaded githound today and configured config.yml as told in the instructions but the path to config.yml was not found.
